project_id = "jrmwivphspbxmacqrava"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
site_url = "https://jrmwivphspbxmacqrava.lovableproject.com"
additional_redirect_urls = ["http://localhost:5173", "https://jrmwivphspbxmacqrava.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true
email_confirm_url = "https://jrmwivphspbxmacqrava.lovableproject.com/auth/callback"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.send-confirmation-email]
verify_jwt = false

[analytics]
enabled = false